set(CMAKE_SYSTEM_NAME Linux)
set(CMAKE_SYSTEM_PROCESSOR arm)
set(CMAKE_C_COMPILER /opt/cross_compiler_tool/arm-linux-gnueabihf-gcc)
set(CMAKE_CXX_COMPILER /opt/cross_compiler_tool/arm-linux-gnueabihf-g++)
set(CMAKE_FIND_ROOT_PATH /opt/target_sysroot)
